{{- if and .Values.apiserver.enabled .Values.apiserver.tls.enabled (not .Values.apiserver.tls.secretName) (not .Values.apiserver.tls.certManager.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "batch-gateway.apiserver.fullname" . }}-tls
  labels:
    {{- include "batch-gateway.apiserver.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.apiserver.tls.cert | b64enc }}
  tls.key: {{ .Values.apiserver.tls.key | b64enc }}
{{- end }}
