{{- if and .Values.apiserver.enabled .Values.apiserver.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "batch-gateway.apiserver.serviceAccountName" . }}
  labels:
    {{- include "batch-gateway.apiserver.labels" . | nindent 4 }}
  {{- with .Values.apiserver.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.apiserver.serviceAccount.automount }}
{{- end }}
