{{- if and .Values.apiserver.enabled .Values.apiserver.tls.enabled .Values.apiserver.tls.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "batch-gateway.apiserver.fullname" . }}-tls
  labels:
    {{- include "batch-gateway.apiserver.labels" . | nindent 4 }}
spec:
  secretName: {{ include "batch-gateway.apiserver.fullname" . }}-tls
  issuerRef:
    name: {{ .Values.apiserver.tls.certManager.issuerName }}
    kind: {{ .Values.apiserver.tls.certManager.issuerKind }}
  dnsNames:
    {{- range .Values.apiserver.ingress.hosts }}
    - {{ .host }}
    {{- end }}
{{- end }}
