{{- if .Values.apiserver.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "batch-gateway.apiserver.fullname" . }}
  labels:
    {{- include "batch-gateway.apiserver.labels" . | nindent 4 }}
  {{- with .Values.apiserver.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.apiserver.service.type }}
  ports:
    - port: {{ .Values.apiserver.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "batch-gateway.apiserver.selectorLabels" . | nindent 4 }}
{{- end }}
