{{- if and .Values.processor.enabled .Values.processor.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "batch-gateway.processor.serviceAccountName" . }}
  labels:
    {{- include "batch-gateway.processor.labels" . | nindent 4 }}
  {{- with .Values.processor.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.processor.serviceAccount.automount }}
{{- end }}
