{{- if and .Values.processor.enabled .Values.processor.tls.enabled (not .Values.processor.tls.secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "batch-gateway.processor.fullname" . }}-tls
  labels:
    {{- include "batch-gateway.processor.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.processor.tls.cert | b64enc }}
  tls.key: {{ .Values.processor.tls.key | b64enc }}
{{- end }}
